<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="https://tierno.es/clinica"
    elementFormDefault="qualified">
    <xs:element name="clinica">
        <xs:complexType>
            <!-- secuencia: especialidad-->
            <xs:sequence>
                <xs:element name="especialidad">
                    <xs:complexType>
                        <!-- secuencia: medico-->
                        <xs:sequence>
                           <!-- TODO --> 
                        </xs:sequence>
                        <!--atributo: area-->
                        <!-- TODO --> 
                    </xs:complexType>
                </xs:element>
            </xs:sequence>

            <!-- atributos: nombre y ciudad-->
            <xs:attribute name="nombre" type="xs:string" />
            <xs:attribute name="ciudad" type="xs:string" />
        </xs:complexType>
    </xs:element>

</xs:schema>