<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://tierno.es/catalog"
    elementFormDefault="qualified"
    xmlns:tns="http://tierno.es/catalog">
    <xs:element name="catalog">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="movie" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string" />
                            <xs:element name="year" type="tns:YearType"/>
                            <xs:element name="genre" type="tns:GenreType" maxOccurs="unbounded"/>
                            <xs:element name="rating" type="tns:RatingType" minOccurs="0"/>
                            <xs:element name="director" type="tns:DirectorType"/>
                            <xs:element name="duration" type="xs:positiveInteger"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- definiciones de tipos: -->
    <xs:simpleType name="YearType">
        <xs:restriction base="xs:positiveInteger">
            <xs:minExclusive value="1900" />
            <xs:maxExclusive value="2024" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="GenreType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="action"/>
            <xs:enumeration value="comedy"/>
            <xs:enumeration value="drama"/>
            <xs:enumeration value="sci-fi"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="RatingType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="PG"/>
            <xs:enumeration value="PG-13"/>
            <xs:enumeration value="R"/>
            <xs:enumeration value="NC-17"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="DirectorType">
        <xs:simpleContent>
            <xs:restriction base="xs:string">
                <xs:attribute name="nationality"/>
            </xs:restriction>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>